/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment10;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
    Sword espada = new Sword(20, 1000, "fire sword");
    Inventory nuevo = new Inventory(3,20);
    
    Tonic inti = new Tonic("curar", "tonico inti", 20);
    Poison veneno = new Poison("envenenar", "veneno de clash", -20);
    nuevo.addItem(inti);
    nuevo.addItem(espada);
    //nuevo.moveItem(inti, 15);
    //nuevo.ver(1, 0);
    //nuevo.searchItem(inti);
    nuevo.useItem(veneno);
    }
}
